import React from "react";

export default function Footer() {
  return (
    <div className="footer init">
      <div className="footer__content init__c">
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>
        Footer
        <br></br>


      </div>
    </div>
  );
}
